Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mask_ccdmask = CCDData.read(ex2_path / 'mask_from_ccdmask.fits', unit=u.dimensionless_unscaled)
mask_ccdmask.data = mask_ccdmask.data.astype('bool')

mask_hot_pix = CCDData.read(ex2_path / 'mask_from_dark_current.fits', unit=u.dimensionless_unscaled)
mask_hot_pix.data = mask_hot_pix.data.astype('bool')
------------------

[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[3][39m[32m, line 1[39m
[32m----> [39m[32m1[39m mask_ccdmask = [43mCCDData[49m[43m.[49m[43mread[49m[43m([49m[43mex2_path[49m[43m [49m[43m/[49m[43m [49m[33;43m'[39;49m[33;43mmask_from_ccdmask.fits[39;49m[33;43m'[39;49m[43m,[49m[43m [49m[43munit[49m[43m=[49m[43mu[49m[43m.[49m[43mdimensionless_unscaled[49m[43m)[49m
[32m      2[39m mask_ccdmask.data = mask_ccdmask.data.astype([33m'[39m[33mbool[39m[33m'[39m)
[32m      4[39m mask_hot_pix = CCDData.read(ex2_path / [33m'[39m[33mmask_from_dark_current.fits[39m[33m'[39m, unit=u.dimensionless_unscaled)

[36mFile [39m[32m~/miniconda3/envs/mamba/lib/python3.11/site-packages/astropy/nddata/mixins/ndio.py:59[39m, in [36mNDDataRead.__call__[39m[34m(self, *args, **kwargs)[39m
[32m     58[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34m__call__[39m([38;5;28mself[39m, *args, **kwargs):
[32m---> [39m[32m59[39m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43mregistry[49m[43m.[49m[43mread[49m[43m([49m[38;5;28;43mself[39;49m[43m.[49m[43m_cls[49m[43m,[49m[43m [49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m

[36mFile [39m[32m~/miniconda3/envs/mamba/lib/python3.11/site-packages/astropy/io/registry/core.py:200[39m, in [36mUnifiedInputRegistry.read[39m[34m(self, cls, format, cache, *args, **kwargs)[39m
[32m    196[39m [38;5;28;01mtry[39;00m:
[32m    197[39m     ctx = get_readable_fileobj(
[32m    198[39m         args[[32m0[39m], encoding=[33m"[39m[33mbinary[39m[33m"[39m, cache=cache
[32m    199[39m     )
[32m--> [39m[32m200[39m     fileobj = [43mctx[49m[43m.[49m[34;43m__enter__[39;49m[43m([49m[43m)[49m
[32m    201[39m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[32m    202[39m     [38;5;28;01mraise[39;00m

[36mFile [39m[32m~/miniconda3/envs/mamba/lib/python3.11/contextlib.py:137[39m, in [36m_GeneratorContextManager.__enter__[39m[34m(self)[39m
[32m    135[39m [38;5;28;01mdel[39;00m [38;5;28mself[39m.args, [38;5;28mself[39m.kwds, [38;5;28mself[39m.func
[32m    136[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m137[39m     [38;5;28;01mreturn[39;00m [38;5;28mnext[39m([38;5;28mself[39m.gen)
[32m    138[39m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[32m    139[39m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([33m"[39m[33mgenerator didn[39m[33m'[39m[33mt yield[39m[33m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;28;01mNone[39;00m

[36mFile [39m[32m~/miniconda3/envs/mamba/lib/python3.11/site-packages/astropy/utils/data.py:365[39m, in [36mget_readable_fileobj[39m[34m(name_or_obj, encoding, cache, show_progress, remote_timeout, sources, http_headers, use_fsspec, fsspec_kwargs, close_files)[39m
[32m    356[39m [38;5;28;01mif[39;00m is_url:
[32m    357[39m     name_or_obj = download_file(
[32m    358[39m         name_or_obj,
[32m    359[39m         cache=cache,
[32m   (...)[39m[32m    363[39m         http_headers=http_headers,
[32m    364[39m     )
[32m--> [39m[32m365[39m fileobj = [43mio[49m[43m.[49m[43mFileIO[49m[43m([49m[43mname_or_obj[49m[43m,[49m[43m [49m[33;43m"[39;49m[33;43mr[39;49m[33;43m"[39;49m[43m)[49m
[32m    366[39m [38;5;28;01mif[39;00m is_url [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m cache:
[32m    367[39m     delete_fds.append(fileobj)

[31mFileNotFoundError[39m: [Errno 2] No such file or directory: 'example2-reduced/mask_from_ccdmask.fits'
FileNotFoundError: [Errno 2] No such file or directory: 'example2-reduced/mask_from_ccdmask.fits'

